version: '3'

services:
  db:
    image: postgres:latest
    container_name: bakery_bot_test_db
    env_file: ./envs/dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/test_data

  redis:
    image: redis:latest
    container_name: bakery_bot_test_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: